site_name: Teddy Warner
site_description: Portfolio and Documentation Site for Teddy Warner
site_author: Teddy Warner
copyright: Copyright 2021 Teddy Warner - Creative Commons Attribution Non Commercial

site_url: https://teddywarner.org/

repo_url: https://github.com/Twarner491/Project-Documentation-Site
repo_name: Twarner491/project-site

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/teddy-warner-880974200/"
    - icon: fontawesome/brands/github
      link: https://github.com/Twarner491
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/teddywarner
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WarnerTeddy
    - icon: fontawesome/solid/paper-plane
      link: mailto:<Twarner491@gmail.com>

  analytics:
    provider: google
    property: G-DRNQ5C2ZP2

theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode


  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono

  logo: images/TeddyWarner.svg

  favicon: images/TW.svg

  icon:
    repo: fontawesome/brands/git-alt
                                                                            
  features:
   - navigation.top
   - navigation.tabs
   - navigation.expand
   - toc.integrate

plugins:
  - search
  - git-committers:
      repository: Twarner491/Project-Documentation-Site
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - meta

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/index.js 

nav:
  - Home : index.md
  - About Me: About-Me/about.md
  - Projects: 
    - Highlights : highlights.md
    - Project Feed : 
      - Project Portfolio Site : Projects/ProjectPortfolioSite.md
      - Lithophane Experiments: Projects/LithophaneExperiments.md
      - Assistive Aquaponics Tank : Projects/AssistiveAquaponics.md
      - Cable Managed Corner Desk : Projects/CornerDesk.md
      - Klipper Enabled Ender 3: Projects/KlipperEnder3.md
      - UPDI Serial Programmer: Projects/SerialUPDI.md
  - Machine Profiles: 
    - Laser Cutters :
      - Epliog Fusion Pro 48 : Machine-Profiles/FusionPro48.md
    - 3D Printers : 
      - Prusa I3 MK3S+ : Machine-Profiles/MK3S+.md
      - Klipper Enabled Ender 3 : Machine-Profiles/KlipperEnder3Profile.md
  - Fab Academy: "http://fabacademy.org/2021/labs/charlotte/students/theodore-warner/"