site_name: Teddy Warner - Project Documentation Site
site_description: Project Documentation Site for Teddy Warner
site_author: Teddy Warner
copyright: Copyright 2021 Teddy Warner - Creative Commons Attribution Non Commercial

site_url: https://twarner491.github.io/Project-Documentation-Site/

repo_url: https://github.com/Twarner491/Twarner491.github.io
repo_name: Twarner491/project-site

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/teddy-warner-880974200/"
    - icon: fontawesome/brands/github
      link: https://github.com/Twarner491
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/teddywarner
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WarnerTeddy
    - icon: fontawesome/solid/paper-plane
      link: mailto:<Twarner491@gmail.com>

theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode


  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono

  logo: images/OpenSourseHardwarePride.svg

  favicon: images/TW.svg

  icon:
    repo: fontawesome/brands/git-alt
                                                                            
  features:
   - navigation.top
   - navigation.tabs
   - toc.integrate

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - meta

extra_css:
  - stylesheets/extra.css

nav:
  - Home : index.md
  - About Me: About-Me/about.md
  - Projects: 
    - Highlights : highlights.md
    - Assistive Aquaponics Tank : 
      - Assistive Aquaponics Tank : Projects/AssistiveAquaponics.md
    - Corner Desk : 
      - Corner Desk : Projects/CornerDesk.md
    - Klipper Enabled Ender 3:
      - Klipper Enabled Ender 3: Projects/KlipperEnder3.md
    - Lithophane Experiments:
      - Lithophane Experiments: Projects/LithophaneExperiments.md
  - Fab Academy: "http://fabacademy.org/2021/labs/charlotte/students/theodore-warner/"